# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
# begin starcup: command roles are whitelisted
#  requirements:
#    - !type:RoleTimeRequirement
#      role: JobChemist
#      time: 10800 #3 hrs
#    - !type:RoleTimeRequirement
#      role: JobMedicalDoctor
#      time: 21600 #6 hrs
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 36000 #10 hrs
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  whitelisted: true # starcup
# end starcup
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  # begin starcup additions
  - Paramedic
  - Psychologist
  # end starcup additions
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
