- type: gameMapPool
  id: StarcupDefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Byoin # starcup: ported from delta-v
  #- Convex
  #- Core
  - Elkridge
  - Fland
  - Glacier # starcup: ported from Delta-V. enabled.
  #- Gate
  - Loopstarcup
  - Marathon
  #- Meta
  - Oasis
  - Omegastarcup
  - Packedstarcup
  - Plasma
  - Reachstarcup
  - Salternstarcup # starcup: wasn't on the list for some reason? enabled.
  #- Train
