- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
# begin starcup: command roles are whitelisted
#  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Engineering
#      time: 54000 # 15 hours
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 54000 # 15 hours
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 54000 # 15 hours
#    - !type:DepartmentTimeRequirement
#      department: Command
#      time: 54000 # 15 hours
  whitelisted: true # starcup
# end starcup
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    #shoes: ClothingShoesBootsLaceup # - DeltaV - Commented out for loadout options
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
