- type: job
  id: Courier
  name: job-name-courier
  description: job-description-courier
  startingGear: CourierGear
  playTimeTracker: JobCourier
  icon: "JobIconCourier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Mail

- type: startingGear
  id: CourierGear
  equipment:
    ears: ClothingHeadsetCargo
    belt: CourierBag

# begin starcup: add chameleon outfit
- type: chameleonOutfit
  id: CourierChameleonOutfit
  job: Courier
  equipment:
    Head: ClothingHeadCourier
    Eyes: ClothingEyesGlassesCheapSunglasses
    Mask: ClothingMaskBreath
    Neck: ClothingNeckScarfStripedBrown
    OuterClothing: ClothingOuterWinterCargo
    Gloves: ClothingHandsGlovesFingerless
# end starcup
