- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
# begin starcup: command roles are whitelisted
#  requirements:
#    - !type:RoleTimeRequirement
#      role: JobWarden
#      time: 10800 #3 hrs
#    - !type:RoleTimeRequirement
#      role: JobSecurityOfficer
#      time: 36000 #10 hrs
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 108000 # 30 hrs
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
# end starcup
  whitelisted: true # starcup
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
  #  pocket1: WeaponPistolMk58Nonlethal # DeltaV - loadouts
  storage:
    back:
    - Flash
  # - MagazinePistol # DeltaV - loadouts

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
