- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
# begin starcup
#  requirements:
#    - !type:OverallPlaytimeRequirement
#      time: 36000 #10 hrs
#    - !type:DepartmentTimeRequirement # starcup: remove intern lockout
#      department: Security
#      time: 54000 #15 hrs
#      inverted: true # stop playing intern if you're good at security!
# end starcup
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityCadetGear
  equipment:
#    shoes: ClothingShoesBootsJackFilled # starcup, moved to loadout
#    outerClothing: ClothingOuterArmorBasic # starcup, moved to loadout
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponDisabler # DeltaV - loadouts, Security Cadet doesn't spawn with a gun
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: SecurityCadetChameleonOutfit
  job: SecurityCadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesHudSecurity
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckScarfStripedRed
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
