- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
# begin starcup
#  requirements:
#    - !type:OverallPlaytimeRequirement
#      time: 3600 #1 hr
#    - !type:DepartmentTimeRequirement # starcup: remove intern lockout
#      department: Engineering
#      time: 54000 #15 hrs
#      inverted: true # stop playing intern if you're good at engineering!
# end starcup
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
#    shoes: ClothingShoesBootsWork # starcup: replaced by loadout
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: TechnicalAssistantChameleonOutfit
  job: TechnicalAssistant
  equipment:
    head: ClothingHeadHatHardhatOrange
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterVestHazard
    gloves: ClothingHandsGlovesColorYellow
