- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  - Clown # starcup: added unique access level
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ClownGear
  equipment:
#    mask: ClothingMaskClown # starcup: replaced with loadout
    pocket1: BikeHorn
    pocket2: ClownRecorder
#    id: ClownPDA # DeltaV: different PDAs in loadouts
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow

- type: chameleonOutfit
  id: ClownChameleonOutfit
  job: Clown
  equipment:
    head: ClothingHeadHatXmasCrown
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
    gloves: ClothingHandsGlovesColorYellowBudget
