- type: entity
  id: NanotrasenMicrowaveMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: NanoTrasen microwave machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: NanotrasenMicrowave
      stackRequirements:
        Capacitor: 1
        Glass: 2
        Cable: 2
