name: "Labels: Review"

on:
  pull_request_target:
<<<<<<< HEAD
    types: [review_requested, opened]
=======
    types: [review_requested]
>>>>>>> 0b8c0e153f (i fucking did it (labeler fixes FOR REAL) (#2993))

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "S: Awaiting Changes"
